<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;


class CreateDevices extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up() {

		//
		// Core Schema
		//

		Schema::create('device', function (Blueprint $table) {

			$table
				->increments('id')
				->unsigned()
			;

			$table
				->tinyInteger('platform_id')
				->unsigned()
			;

			// Unique identifier, based on & generated by the client.
			$table->string('hardware_id');

			// Version string supplied by the client.
			$table->string('version');

			// The hardware-vendor-specific push token.
			$table
				->string('push_token')
				->nullable()
			;

			// Sound??
			$table
				->tinyInteger('sound')
				->unsigned()
				->nullable()
			;

			// Standard timezone string for a device.  These come in the form of an area/location pair.
			// See http://en.wikipedia.org/wiki/Tz_database for more details.
			$table->string('timezone');

			//
			// Representation of the time window within which a device can receive pushes.
			//
			$table
				->integer('push_from')
				->nullable()
			;
			$table
				->integer('push_to')
				->nullable()
			;

			$table
				->dateTime('disabled_at')
				->nullable()
			;

			$table
				->tinyInteger('invalid_count')
				->nullable()
			;

			$table
				->dateTime('invalidated_at')
				->nullable()
			;

			// Use standard timestamps.
			$table->timestamps();

			//
			//
			//

			$table->unique('push_token', 'U_push_token');
			$table->unique('hardware_id', 'U_hardware_id');

		});

	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down() {
		Schema::dropIfExists('device');
	}

}